version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db

  catalogdbgui:
    container_name: catalogdbgui
    restart: always
    environment:
      - MONGO_URL=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    ports:
        - "3000:3000"

  catalog.api:
    container_name: catalog.api
    environment:
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"